### ISSUE TITLE
Error on init sqlite DB

### ISSUE THREAD

**Issue by MartinBucko** [alecdibble/nama#5]
https://github.com/alecdibble/nama/blob/d4628ef79131753b9b1f4456bdac2548143f9a2a/src/services/db.js#L16

```
PRIMARY_KEY shoud be PRIMARY KEY withouth "_" 
```

Thanks and good luck :)

**Comment by alecdibble** [comment]
Thanks for reporting! Should be fixed with this commit: https://github.com/alecdibble/nama/commit/651d5ea189c32051ea233f345961832becd0a7ac
